package gui.user.selTipoCliente;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import gui.Frame;
import gui.user.altaCliente.AltaCliente;
import gui.user.altaEmpresa.AltaEmpresa;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SelTipoCliente extends JPanel implements Frame {
    private JButton PersFisButton;
    private JButton EmpresaButton;
    private JPanel root;

    public SelTipoCliente() {
        add(root);
        ActionListener persfisica = (e) -> {
            var panel = new AltaCliente();
            var frame = new JFrame(panel.getTitleBarName());
            frame.setMenuBar(panel.getMenuBar());
            frame.add(panel);
            frame.pack();
            frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            frame.setLocationRelativeTo(null);
            frame.setSize(frame.getSize());
            frame.setVisible(true);
        };

        ActionListener empresa = (e) -> {
            var panel = new AltaEmpresa();
            var frame = new JFrame(panel.getTitleBarName());
            frame.setMenuBar(panel.getMenuBar());
            frame.add(panel);
            frame.pack();
            frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            frame.setLocationRelativeTo(null);
            frame.setSize(frame.getSize());
            frame.setVisible(true);
        };

        PersFisButton.addActionListener(persfisica);
        EmpresaButton.addActionListener(empresa);

    }

    @Override
    public String getTitleBarName() {
        return "Seleccionar tipo de cliente";
    }

    @Override
    public MenuBar getMenuBar() {
        return null;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        root.setPreferredSize(new Dimension(400, 200));
        PersFisButton = new JButton();
        PersFisButton.setText("PERSONA FÍSICA");
        root.add(PersFisButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        EmpresaButton = new JButton();
        EmpresaButton.setText("EMPRESA");
        root.add(EmpresaButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}
