package gui.alemania;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jcraft.jsch.ChannelSftp;
import com.jcraft.jsch.JSch;
import database.HibernateStartUp;
import database.tables.EburyAccountEntity;
import gui.Frame;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ExecutionException;

public class Informe extends JPanel implements Frame {
    private JButton primerInformeButton;
    private JTable csvPreviewTable;
    private JButton informeSemanalButton;
    private JButton enviarSFTPButton;
    private JButton exportarButton;
    private JScrollPane scrollPane;
    private JPanel root;

    public Informe() {
        add(root);
        exportarButton.addActionListener(e -> {
            var filechooser = new JFileChooser();
            filechooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            filechooser.setMultiSelectionEnabled(false);
            var result = filechooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                var folder = filechooser.getSelectedFile();
                var file = new File(folder, "export.csv");
                var save = new GuardarCSVWorker(this, file);
                save.execute();
            }
        });
        informeSemanalButton.addActionListener(e -> {
            var g = new GenerarInformeSemanalWorker(this);
            g.execute();
        });
        enviarSFTPButton.addActionListener(e -> {
            var ip = new JTextField();
            var username = new JTextField();
            var pass = new JPasswordField();
            var dest = new JTextField();
            dest.setText("/");
            var components = new JComponent[]{
                    new JLabel("Host"),
                    ip,
                    new JLabel("Username"),
                    username,
                    new JLabel("Password"),
                    pass,
                    new JLabel("Destino"),
                    dest
            };
            var res = JOptionPane.showConfirmDialog(this, components, "Enviar por SFTP", JOptionPane.PLAIN_MESSAGE);
            if (res == JOptionPane.OK_OPTION) {
                Path temp = null;
                try {
                    temp = Files.createTempFile(new Date().toString(), ".csv");
                    var worker = new SFTPWorker(this,
                            temp.toFile(),
                            ip.getText(),
                            username.getText(),
                            String.valueOf(pass.getPassword()),
                            dest.getText());
                    worker.execute();
                } catch (IOException ex) {
                    ex.printStackTrace();
                    var m = ex.getMessage();
                    JOptionPane.showMessageDialog(this, m, m, JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    private void lockUI() {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        this.enviarSFTPButton.setEnabled(false);
        this.informeSemanalButton.setEnabled(false);
        this.primerInformeButton.setEnabled(false);
        this.exportarButton.setEnabled(false);

    }

    private void unlockUI() {
        setCursor(Cursor.getDefaultCursor());
        this.enviarSFTPButton.setEnabled(true);
        this.informeSemanalButton.setEnabled(true);
        this.primerInformeButton.setEnabled(true);
        this.exportarButton.setEnabled(true);
    }

    @Override
    public String getTitleBarName() {
        return "Informe Alemania";
    }

    @Override
    public MenuBar getMenuBar() {
        return null;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        root.setOpaque(true);
        root.setPreferredSize(new Dimension(1250, 500));
        primerInformeButton = new JButton();
        primerInformeButton.setText("Generar Primer Informe");
        root.add(primerInformeButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        informeSemanalButton = new JButton();
        informeSemanalButton.setText("Generar Informe Semanal");
        root.add(informeSemanalButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        enviarSFTPButton = new JButton();
        enviarSFTPButton.setEnabled(true);
        enviarSFTPButton.setText("Enviar por SFTP");
        root.add(enviarSFTPButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        root.add(spacer1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        exportarButton = new JButton();
        exportarButton.setEnabled(true);
        exportarButton.setText("Exportar...");
        root.add(exportarButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollPane = new JScrollPane();
        root.add(scrollPane, new GridConstraints(0, 0, 5, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        csvPreviewTable = new JTable();
        csvPreviewTable.setAutoResizeMode(0);
        csvPreviewTable.setCellSelectionEnabled(false);
        csvPreviewTable.setEnabled(false);
        scrollPane.setViewportView(csvPreviewTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

    private class SFTPWorker extends GuardarCSVWorker {
        String ip;
        String username;
        String pass;
        String dest;

        public SFTPWorker(Informe informe, File temp, String ip, String username, String pass, String dest) {
            super(informe, temp);
            this.ip = ip;
            this.username = username;
            this.pass = pass;
            this.dest = dest;
        }

        @Override
        protected Void doInBackground() throws Exception {
            super.doInBackground();

            var frame = new JFrame("Send");
            var sending = new JLabel("Sending file");
            frame.add(sending);
            frame.setUndecorated(true);
            frame.pack();
            frame.setLocationRelativeTo(informe);
            frame.setVisible(true);

            try {
                var jsch = new JSch();
                var session = jsch.getSession(username, ip);
                session.setConfig("StrictHostKeyChecking", "no");
                session.setPassword(pass);
                session.connect();
                var channel = (ChannelSftp) session.openChannel("sftp");
                channel.connect();
                channel.put(file.getAbsolutePath(), dest);
                channel.exit();
                var m = "Archivo enviado";
                JOptionPane.showMessageDialog(informe, m, m, JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                ex.printStackTrace();
                var m = ex.getMessage();
                JOptionPane.showMessageDialog(informe, m, m, JOptionPane.ERROR_MESSAGE);
            } finally {
                frame.dispose();
            }
            return null;
        }

        @Override
        protected void done() {
            unlockUI();
        }
    }

    private class GuardarCSVWorker extends SwingWorker<Void, Void> {
        Informe informe;
        File file;

        public GuardarCSVWorker(Informe informe, File file) {
            this.informe = informe;
            this.file = file;
        }

        @Override
        protected Void doInBackground() throws Exception {
            lockUI();
            var frame = new JFrame("Save");
            var progress = new JProgressBar();
            frame.add(progress);
            frame.setUndecorated(true);
            frame.pack();
            frame.setLocationRelativeTo(informe);
            frame.setVisible(true);
            generateCSV(frame, progress);
            return null;
        }

        private void generateCSV(JFrame frame, JProgressBar progress) {
            var model = csvPreviewTable.getModel();
            progress.setMaximum(model.getRowCount());
            try (var csv = new FileWriter(file)) {
                // TODO añade un montón de columnas que no deberían estar
                for (int i = 0; i < model.getColumnCount() - 1; i++) {
                    csv.write(model.getColumnName(i) + ",");
                }
                csv.write(model.getColumnName(model.getColumnCount() - 1));
                csv.write("\n");
                for (int i = 0; i < model.getRowCount(); i++) {
                    for (int j = 0; j < model.getColumnCount() - 1; j++) {
                        var value = model.getValueAt(i, j).toString();
                        var safeValue = value.replace(",", "");
                        csv.write(safeValue + ",");
                    }
                    csv.write(model.getValueAt(i, model.getColumnCount() - 1).toString().replace(',', Character.MIN_VALUE));
                    progress.setValue(i);
                    csv.write("\n");
                }
                var m = "Exportación correcta";
                JOptionPane.showMessageDialog(frame, m, m, JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                ex.printStackTrace();
                var m = ex.getMessage();
                JOptionPane.showMessageDialog(frame, m, m, JOptionPane.ERROR_MESSAGE);
            } finally {
                frame.dispose();
            }
        }

        @Override
        protected void done() {
            unlockUI();
        }
    }

    private class GenerarPrimerInformeWorker extends SwingWorker<List<Object>, Void> {
        Informe informe;

        public GenerarPrimerInformeWorker(Informe informe) {
            this.informe = informe;
        }

        @Override
        protected List<Object> doInBackground() throws Exception {
            lockUI();
            try (var session = HibernateStartUp.getSessionFactory().openSession()) {
                // TODO querry no es la correcta. Completar
                return session.createQuery("from BankAccountEntity, EburyAccountEntity").list();
            }
        }

        @Override
        protected void done() {
            try {
                var result = get();
                csvPreviewTable.removeAll();
                for (var i : result) {
                    // TODO insertar datos dentro de la tabla
                    //var c = new TableColumn(i);
                    //csvPreviewTable.addColumn(c);
                }
                System.out.println(result);
            } catch (InterruptedException | ExecutionException e) {
                e.printStackTrace();
                var m = e.getMessage();
                JOptionPane.showMessageDialog(informe, m, m, JOptionPane.ERROR_MESSAGE);
            } finally {
                informe.unlockUI();
            }
        }
    }

    private class GenerarInformeSemanalWorker extends SwingWorker<List<EburyAccountEntity>, Void> {
        Informe informe;

        public GenerarInformeSemanalWorker(Informe informe) {
            this.informe = informe;
        }

        @Override
        protected List<EburyAccountEntity> doInBackground() throws Exception {
            lockUI();
            try (var session = HibernateStartUp.getSessionFactory().openSession()) {
                return session.createQuery("from EburyAccountEntity").list();
            }
        }

        @Override
        protected void done() {
            try {
                var result = get();
                csvPreviewTable.removeAll();
                // TODO no está bien del todo. Mirar las diapositivas del profesor
                var tablemodel = new DefaultTableModel(new String[]{"IBAN", "Nombre", "Dirección", "NIF", "Fecha Nacimiento/Creación"}, 0);

                for (var i : result) {
                    var cuentabanc = i.getBankAccount();
                    var duenyo = i.getOwner();
                    tablemodel.addRow(
                            new Object[]{
                                    cuentabanc.getIban(),
                                    duenyo.fullName(),
                                    duenyo.getDireccion() == null ? "noexistente" : duenyo.getDireccion().toString(),
                                    duenyo.getNif(),
                                    duenyo.getBirthDate() == null ? "noexistente" : duenyo.getBirthDate().toString()
                            });
                }
                csvPreviewTable.setModel(tablemodel);
                resizeColumnWidth(csvPreviewTable);
            } catch (InterruptedException | ExecutionException e) {
                e.printStackTrace();
                var m = e.getMessage();
                JOptionPane.showMessageDialog(informe, m, m, JOptionPane.ERROR_MESSAGE);
            } finally {
                informe.unlockUI();
            }
        }

        public void resizeColumnWidth(JTable table) {
            final TableColumnModel columnModel = table.getColumnModel();
            for (int column = 0; column < table.getColumnCount(); column++) {
                int width = 15; // Min width
                for (int row = 0; row < table.getRowCount(); row++) {
                    TableCellRenderer renderer = table.getCellRenderer(row, column);
                    Component comp = table.prepareRenderer(renderer, row, column);
                    width = Math.max(comp.getPreferredSize().width + 1, width);
                }
                if (width > 300)
                    width = 300;
                columnModel.getColumn(column).setPreferredWidth(width);
            }
        }
    }

}
