package gui.user;

import com.intellij.uiDesigner.core.GridLayoutManager;
import database.tables.LoginEntity;
import gui.Frame;

import javax.swing.*;
import java.awt.*;

public class MainPanel extends JPanel implements Frame {
    LoginEntity login;

    public MainPanel(LoginEntity login) {
        this.login = login;
    }

    @Override
    public String getTitleBarName() {
        // TODO
        return "Bienvenido " + login.getUser();
    }

    @Override
    public MenuBar getMenuBar() {
        return null;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
